# Generated by Django 2.2.6 on 2019-10-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191026_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
